/* config.h — HobbyOS port configuration for GNU nano 8.7.
 *
 * Upstream, this file is generated by configure from config.h.in.  The port
 * keeps nano's sources byte-identical and pins the configuration here, the
 * same way src/user/sed/config.h does for GNU sed.
 *
 * The port's feature choices, and why:
 *
 *   no ENABLE_UTF8      — no multibyte/wide-char support in the sysroot;
 *                         nano falls back to its single-byte paths
 *                         (chars.c has clean #else arms for every helper).
 *   no ENABLE_COLOR     — no terminfo database to name colours; nano's
 *                         monochrome interface colours (A_REVERSE) are what
 *                         a stock nano looks like anyway.  color.c compiles
 *                         to nothing.
 *   no ENABLE_MOUSE     — the desktop has its own mouse protocol (OSC P);
 *                         nano's ncurses mouse API has no backend here.
 *   no ENABLE_NANORC    — needs glob(3) + pwd.h; no syntax/rc files exist in
 *                         the HobbyOS root anyway.
 *   no ENABLE_HISTORIES — needs a writable ~ directory and pwd.h; kept off
 *                         so nano never tries to save state it cannot find.
 *   no ENABLE_SPELLER / ENABLE_FORMATTER / ENABLE_LINTER
 *                       — all of them fork+popen, which the sysroot does
 *                         not have yet (no fork, no pipes).
 *   no ENABLE_OPERATINGDIR — chroot-style confinement is meaningless here.
 *   no ENABLE_EXTRA     — upstream's "extra" bits (mode line, etc).
 *   no ENABLE_NLS       — no libintl/gettext; English help text.
 *
 * Everything else is upstream's full-feature default: multibuffer, justify,
 * comment/uncomment, word completion, the help viewer, soft wrapping,
 * line numbers, and (below, via ENABLE_BROWSER/ENABLE_TABCOMP, once the
 * sysroot dirent layer works) the file browser and tab completion.
 */

#define PACKAGE "nano"
#define PACKAGE_NAME "GNU nano"
#define PACKAGE_VERSION "8.7"
#define PACKAGE_STRING "GNU nano 8.7"
#define PACKAGE_BUGREPORT "nano-devel@gnu.org"

/* ---- feature gates -------------------------------------------------- */

/* Upstream defaults we keep. */
#define ENABLE_HELP 1
#define ENABLE_MULTIBUFFER 1
#define ENABLE_JUSTIFY 1
#define ENABLE_COMMENT 1
#define ENABLE_WORDCOMPLETION 1
#define ENABLE_WRAPPING 1
#define ENABLE_LINENUMBERS 1

/* HobbyOS scope: off for this port (see the header comment). */
/* #undef ENABLE_UTF8 */
/* #undef ENABLE_COLOR */
/* #undef ENABLE_MOUSE */
/* #undef ENABLE_NANORC */
/* #undef ENABLE_HISTORIES */
/* #undef ENABLE_SPELLER */
/* #undef ENABLE_FORMATTER */
/* #undef ENABLE_LINTER */
/* #undef ENABLE_OPERATINGDIR */
/* #undef ENABLE_EXTRA */
/* #undef ENABLE_NLS */

/* Kept off until the sysroot gains a real opendir/readdir (the port's
 * src/user/nano/README.md tracks this). */
/* #undef ENABLE_BROWSER */
/* #undef ENABLE_TABCOMP */

/* ---- system capability probes ---------------------------------------- */

#define HAVE_CONFIG_H 1
#define HAVE_LIMITS_H 1
#define HAVE_SYS_PARAM_H 1

/* nano probes terminal settings via a real tty; the desktop pipes are not
 * ttys and the curses shim owns terminal modes, so skip all of it.  With
 * HAVE_TERMIOS_H undefined nano compiles tcgetattr/tcsetattr calls into
 * nothing (nano.c has an #else arm that no-ops them). */
/* #undef HAVE_TERMIOS_H */

/* No pwd.h in the sysroot: skips getpwuid-based branches (backup-file
 * suffixes, nanorc include globs, history file paths). */
/* #undef HAVE_PWD_H */
/* #undef HAVE_GETEUID */

/* No process primitives yet (no fork/pipe/waitpid in the sysroot). */
/* #undef HAVE_FORK */
/* #undef HAVE_PIPE */
/* #undef HAVE_WAITPID */
/* #undef HAVE_WAIT */

/* No chmod/chown/fsync/flockfile in the sysroot yet. */
/* #undef HAVE_CHMOD */
/* #undef HAVE_FCHMOD */
/* #undef HAVE_CHOWN */
/* #undef HAVE_FCHOWN */
/* #undef HAVE_FSYNC */
/* #undef HAVE_FLOCKFILE */
/* #undef HAVE_FUNLOCKFILE */

/* Curse extensions the shim does not implement: keep the feature off. */
/* #undef HAVE_NCURSES_H */
/* #undef HAVE_KEY_DEFINED */
/* #undef HAVE_SET_ESCDELAY */
/* #undef HAVE_USE_DEFAULT_COLORS */

/* No file(1)/libmagic, no gettext. */
/* #undef HAVE_MAGIC_H */
/* #undef HAVE_LIBMAGIC */
/* #undef HAVE_LIBINTL_H */

/* Let nano know it can trust a <stdint.h> and friends (all in the sysroot). */
#define HAVE_STDINT_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_DIRENT_H 1
#define HAVE_SIGNAL_H 1
#define HAVE_UNISTD_H 1
#define HAVE_STRING_H 1
#define HAVE_CTYPE_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STDIO_H 1
#define HAVE_ERRNO_H 1
#define HAVE_FCNTL_H 1
#define HAVE_REGEX_H 1
#define HAVE_GETOPT_H 1

/* The regex flavour nano compiles its quoting regex with (configure probes
 * for REG_ENHANCED; plain POSIX extended is what the sysroot regex has). */
#define NANO_REG_EXTENDED REG_EXTENDED

/* Upstream builds with assertions compiled out. */
#define NDEBUG 1
