#ifdef KERNEL_MODE_UNIT_TEST

#include "unit_test.h"
#include "fat16.h"
#include "fs.h"

/* Generated by the Makefile from obj/$(ARCH)/unexpand_test.bin — see the
 * UNEXPAND_SIZE_HDR rule; the size is per-arch/per-toolchain. */
#include "unexpand_size_gen.h"

static void test_fat16_open_existing(void) {
  uart_puts("  Running test_fat16_open_existing...\n");
  tests_run++;

  struct file f;
  int res = fat16_open("TEST.TXT", &f);
  EXPECT_EQ(res, 0);
  EXPECT_EQ(f.fat16.cursor, 0);

  fat16_close(&f);
}

static void test_fat16_open_nonexistent(void) {
  uart_puts("  Running test_fat16_open_nonexistent...\n");
  tests_run++;

  /* fat16_open() has create-on-open semantics: opening a file that does not
   * exist creates it and returns 0 (the editor's Save flow relies on this).
   * So a missing file in an existing directory is NOT an error. It fails
   * only when the file cannot be created — e.g. its parent directory does
   * not exist. */
  struct file f;
  int res = fat16_open("/NOSUCHDIR/MISSING.TXT", &f);
  EXPECT_EQ(res, -1);
}

static void test_fat16_read_file(void) {
  uart_puts("  Running test_fat16_read_file...\n");
  tests_run++;

  struct file f;
  int res = fat16_open("TEST.TXT", &f);
  EXPECT_EQ(res, 0);

  char buf[128] = {0};
  int bytes_read = fat16_read(&f, buf, sizeof(buf));
  // Since TEST.TXT is empty or just created by touch, it might be 0 bytes.
  // Wait, the Makefile just does `touch TEST.TXT` so it is 0 bytes.
  EXPECT_EQ(bytes_read, 0);

  fat16_close(&f);
}

static void test_fat16_move_across_dirs(void) {
  uart_puts("  Running test_fat16_move_across_dirs...\n");
  tests_run++;

  struct fat16_dir_entry e;
  struct file f;

  /* Set up: two directories and a file in the root. */
  (void)fat16_mkdir("/MOVEDIR");
  (void)fat16_mkdir("/MOVEDIR2");
  EXPECT_EQ(fat16_open("/MOVE.TXT", &f), 0);
  fat16_close(&f);

  /* Move a file into a subdirectory. */
  EXPECT_EQ(fat16_rename("/MOVE.TXT", "/MOVEDIR/MOVE.TXT"), 0);
  ASSERT(fat16_resolve_path("/MOVE.TXT", &e, 0, 0) != 0);
  EXPECT_EQ(fat16_resolve_path("/MOVEDIR/MOVE.TXT", &e, 0, 0), 0);

  /* Rename in place inside that directory. */
  EXPECT_EQ(fat16_rename("/MOVEDIR/MOVE.TXT", "/MOVEDIR/RENAMED.TXT"), 0);
  ASSERT(fat16_resolve_path("/MOVEDIR/MOVE.TXT", &e, 0, 0) != 0);
  EXPECT_EQ(fat16_resolve_path("/MOVEDIR/RENAMED.TXT", &e, 0, 0), 0);

  /* POSIX rename semantics: an existing destination is replaced, not a
   * rename failure (sed -i and mv both depend on this). */
  EXPECT_EQ(fat16_open("/CLOB1.TXT", &f), 0);
  fat16_close(&f);
  EXPECT_EQ(fat16_open("/MOVEDIR/CLOB2.TXT", &f), 0);
  fat16_close(&f);
  EXPECT_EQ(fat16_rename("/CLOB1.TXT", "/MOVEDIR/CLOB2.TXT"), 0);
  ASSERT(fat16_resolve_path("/CLOB1.TXT", &e, 0, 0) != 0);
  EXPECT_EQ(fat16_resolve_path("/MOVEDIR/CLOB2.TXT", &e, 0, 0), 0);

  /* Same-directory replace: the exact shape sed -i performs (temp file
   * renamed over the original in the same directory). */
  EXPECT_EQ(fat16_open("/SAME1.TXT", &f), 0);
  fat16_close(&f);
  EXPECT_EQ(fat16_open("/SAME2.TXT", &f), 0);
  fat16_close(&f);
  EXPECT_EQ(fat16_rename("/SAME1.TXT", "/SAME2.TXT"), 0);
  ASSERT(fat16_resolve_path("/SAME1.TXT", &e, 0, 0) != 0);
  EXPECT_EQ(fat16_resolve_path("/SAME2.TXT", &e, 0, 0), 0);

  /* fat16_truncate empties a file: old content gone, new writes land at 0. */
  {
    struct file wf;
    EXPECT_EQ(fat16_open("/TRUNC.TXT", &wf), 0);
    const char *seed = "PLENTY OF OLD CONTENT";
    EXPECT_EQ(fat16_write(&wf, seed, 21), 21);
    fat16_close(&wf);

    EXPECT_EQ(fat16_open("/TRUNC.TXT", &wf), 0);
    EXPECT_EQ(fat16_truncate(&wf), 0);
    const char *fresh = "new";
    EXPECT_EQ(fat16_write(&wf, fresh, 3), 3);
    fat16_close(&wf);

    EXPECT_EQ(fat16_open("/TRUNC.TXT", &wf), 0);
    ASSERT(fat16_seek(&wf, 0) == 0);
    char rbuf[8] = {0};
    int rn = fat16_read(&wf, rbuf, 8);
    fat16_close(&wf);
    EXPECT_EQ(rn, 3);
    if (rn == 3) {
      EXPECT_EQ(rbuf[0], 'n');
      EXPECT_EQ(rbuf[1], 'e');
      EXPECT_EQ(rbuf[2], 'w');
    }
  }

  /* Move a directory, then keep using it. */
  EXPECT_EQ(fat16_mkdir("/MOVESUB"), 0);
  EXPECT_EQ(fat16_rename("/MOVESUB", "/MOVEDIR2/MOVESUB"), 0);
  EXPECT_EQ(fat16_resolve_path("/MOVEDIR2/MOVESUB", &e, 0, 0), 0);
  EXPECT_EQ(fat16_open("/MOVEDIR2/MOVESUB/INNER.TXT", &f), 0);
  fat16_close(&f);
  EXPECT_EQ(fat16_resolve_path("/MOVEDIR2/MOVESUB/INNER.TXT", &e, 0, 0), 0);

  /* The moved directory's ".." must now point at its new parent: moving
   * its parent into it has to be refused as a cycle. */
  EXPECT_EQ(fat16_rename("/MOVEDIR2", "/MOVEDIR2/MOVESUB/MOVEDIR2"), -1);

  /* Missing sources fail. */
  EXPECT_EQ(fat16_rename("/NO-SUCH-FILE.TXT", "/X.TXT"), -1);
  EXPECT_EQ(fat16_rename("/CLOB1.TXT", "/NO-SUCH-DIR/X.TXT"), -1);
}

static void test_fat16_lfn_names(void) {
  uart_puts("  Running test_fat16_lfn_names...\n");
  tests_run++;

  struct fat16_dir_entry e;

  /* 1. A mtools-created long name (0x0F records on disk) must open by its
     long name, not by truncation onto some other entry.  This is exactly
     the bug that made the UNEXPAND_T.BIN wave test load UNEXPAND.BIN. */
  {
    struct file f;
    EXPECT_EQ(fat16_open("/UNEXPAND_T.BIN", &f), 0);
    /* the on-device test binary; the size constant is generated by the build
       (obj/$(ARCH)/unexpand_size_gen.h) because it moves with arch+toolchain */
    EXPECT_EQ(f.fat16.entry.file_size, UNEXPAND_T_BIN_SIZE);
    fat16_close(&f);
  }

  /* 2. A created long name round-trips: write, reopen by long name, read
     the content back, and resolve it through the path walker. */
  {
    struct file f;
    const char *seed = "long file body\n";
    EXPECT_EQ(fat16_open("/LONG_FILENAME_TEST.TXT", &f), 0);
    EXPECT_EQ(fat16_write(&f, seed, 15), 15);
    fat16_close(&f);

    EXPECT_EQ(fat16_open("/LONG_FILENAME_TEST.TXT", &f), 0);
    ASSERT(fat16_seek(&f, 0) == 0);
    {
      char rbuf[32] = {0};
      int rn = fat16_read(&f, rbuf, sizeof(rbuf) - 1);
      fat16_close(&f);
      EXPECT_EQ(rn, 15);
      if (rn == 15) {
        EXPECT_EQ(rbuf[0], 'l');
        EXPECT_EQ(rbuf[13], 'y');
        EXPECT_EQ(rbuf[14], '\n');
      }
    }
    EXPECT_EQ(fat16_resolve_path("/LONG_FILENAME_TEST.TXT", &e, 0, 0), 0);
    EXPECT_EQ(e.file_size, 15);
  }

  /* 3. A query that looks like a truncated version of an EXISTING 8.3
     name must not resolve to that file: 'ABCDEFGH_LONG.TXT' must not open
     'ABCDEFGH.TXT'.  A fresh file is created instead (create-on-open), so
     the result carries the new, empty entry rather than the old content. */
  {
    struct file f;
    const char *seed = "0123456789";
    EXPECT_EQ(fat16_open("/ABCDEFGH.TXT", &f), 0);
    EXPECT_EQ(fat16_write(&f, seed, 10), 10);
    fat16_close(&f);

    EXPECT_EQ(fat16_open("/ABCDEFGH_LONG.TXT", &f), 0);
    EXPECT_EQ(f.fat16.entry.file_size, 0); /* new entry, not 'ABCDEFGH.TXT' */
    fat16_close(&f);
    EXPECT_EQ(fat16_resolve_path("/ABCDEFGH.TXT", &e, 0, 0), 0);
    EXPECT_EQ(e.file_size, 10);
  }
}

/* L7 (fat16 large-file lane): the pre-existing >1 MiB create-path defect.
 * Creating a file and writing > ~1 MiB through the kernel's FAT16 path used
 * to leave a directory entry that reads back with file_size 0 (the "v2
 * loader: bad image size 0" class): reopen reports size 0 and the image
 * loader refuses the file.  This pins create -> write(2 MiB) -> close ->
 * reopen -> size + tail-checksum. */
static void test_fat16_large_create_write(void) {
  uart_puts("  Running test_fat16_large_create_write...\n");
  tests_run++;

  const uint32_t TARGET = 2u * 1024u * 1024u; /* 2 MiB, > the 1 MiB boundary */
  const uint32_t STEP = 16u * 1024u;          /* one call spans many clusters */
  uint8_t chunk[STEP];

  /* Pattern: byte at absolute position p is ((p >> 8) ^ (p & 0xFF)) — a
     position-dependent value that a size-0 / short-read would not survive. */
  struct file f;
  EXPECT_EQ(fat16_open("/BIG1M.BIN", &f), 0); /* create-on-open */

  uint32_t pos = 0;
  int ok = 1;
  while (pos < TARGET) {
    uint32_t n = TARGET - pos;
    if (n > STEP) n = STEP;
    for (uint32_t i = 0; i < n; i++) {
      uint32_t p = pos + i;
      chunk[i] = (uint8_t)((p >> 8) ^ (p & 0xFF));
    }
    if (fat16_write(&f, chunk, (int)n) != (int)n) { ok = 0; break; }
    pos += n;
  }
  EXPECT_EQ(ok, 1);

  /* In-memory size right after the writes (the write path must have tracked
     it) — 2097152. */
  EXPECT_EQ(f.fat16.entry.file_size, (int)TARGET);
  fat16_close(&f);

  /* Reopen by path: the on-disk entry must carry the full size.  This is
     the exact read the loader does before mapping an image. */
  struct fat16_dir_entry e;
  EXPECT_EQ(fat16_resolve_path("/BIG1M.BIN", &e, 0, 0), 0);
  EXPECT_EQ(e.file_size, (int)TARGET);

  EXPECT_EQ(fat16_open("/BIG1M.BIN", &f), 0);
  EXPECT_EQ(f.fat16.entry.file_size, (int)TARGET);

  /* Read the tail cluster and checksum it (a size-0 entry would stop the
     read at 0 bytes; a truncated chain would stop it at 1 MiB). */
  uint32_t lo = TARGET > 4096 ? TARGET - 4096 : 0;
  ASSERT(fat16_seek(&f, (int)lo) == 0);
  uint8_t tail[4096];
  int rn = fat16_read(&f, tail, (int)sizeof tail);
  fat16_close(&f);
  EXPECT_EQ(rn, (int)sizeof tail);
  if (rn == (int)sizeof tail) {
    uint32_t sum = 0;
    for (uint32_t i = 0; i < sizeof tail; i++) {
      uint32_t p = lo + i;
      uint8_t want = (uint8_t)((p >> 8) ^ (p & 0xFF));
      if (tail[i] != want) sum++;
    }
    EXPECT_EQ(sum, 0);
  }
}

/* L7 lane: same >1 MiB round-trip but through the LONG-NAME create path
 * (alloc_lfn_run).  The plan records the defect symptom as "attr=0 entries"
 * next to "file_size reads back as 0" — both point at the 0x0F LFN run /
 * short-entry pair, so the long-name create path is the prime suspect that
 * the 8.3-only path (test_fat16_large_create_write) does not cover. */
static void test_fat16_large_lfn_create_write(void) {
  uart_puts("  Running test_fat16_large_lfn_create_write...\n");
  tests_run++;

  const uint32_t TARGET = 2u * 1024u * 1024u;
  const uint32_t STEP = 16u * 1024u;
  uint8_t chunk[STEP];

  struct file f;
  /* Long name: 14 chars, forces a 0x0F LFN run before the short entry. */
  static const char *path = "/BIG_LONGFILE_1MB.BIN";
  EXPECT_EQ(fat16_open(path, &f), 0);

  uint32_t pos = 0;
  int ok = 1;
  while (pos < TARGET) {
    uint32_t n = TARGET - pos;
    if (n > STEP) n = STEP;
    for (uint32_t i = 0; i < n; i++) {
      uint32_t p = pos + i;
      chunk[i] = (uint8_t)((p >> 8) ^ (p & 0xFF));
    }
    if (fat16_write(&f, chunk, (int)n) != (int)n) { ok = 0; break; }
    pos += n;
  }
  EXPECT_EQ(ok, 1);
  fat16_close(&f);

  struct fat16_dir_entry e;
  EXPECT_EQ(fat16_resolve_path(path, &e, 0, 0), 0);
  EXPECT_EQ(e.file_size, (int)TARGET);

  EXPECT_EQ(fat16_open(path, &f), 0);
  EXPECT_EQ(f.fat16.entry.file_size, (int)TARGET);

  uint32_t lo = TARGET > 4096 ? TARGET - 4096 : 0;
  ASSERT(fat16_seek(&f, (int)lo) == 0);
  uint8_t tail[4096];
  int rn = fat16_read(&f, tail, (int)sizeof tail);
  fat16_close(&f);
  EXPECT_EQ(rn, (int)sizeof tail);
  if (rn == (int)sizeof tail) {
    uint32_t sum = 0;
    for (uint32_t i = 0; i < sizeof tail; i++) {
      uint32_t p = lo + i;
      if (tail[i] != (uint8_t)((p >> 8) ^ (p & 0xFF))) sum++;
    }
    EXPECT_EQ(sum, 0);
  }
}

void fat16_test_suite(void) {
  uart_puts("fat16_test_suite:\n");
  test_fat16_open_existing();
  test_fat16_open_nonexistent();
  test_fat16_read_file();
  test_fat16_move_across_dirs();
  test_fat16_lfn_names();
  test_fat16_large_create_write();
  test_fat16_large_lfn_create_write();
}

#endif // KERNEL_MODE_UNIT_TEST
