/*
 * SEDTEST.BIN — in-OS acceptance test for the ported GNU sed 4.8.
 *
 * Walks the golden table in sed_test_cases.h (generated by
 * tools/gen_sed_tests.py from native GNU sed 4.8 — the same sources this
 * repo vendors) and demands byte-exact parity from SED.BIN for every case:
 * stdout bytes, exit status, and any files the case rewrites (-i, w) or
 * reads (r).  SED.BIN is spawned through the real spawn2/pipe path, so the
 * port's crt0 -> get_args -> getopt_long -> file/stdin I/O -> our printf
 * stack is exercised end to end.
 *
 * The fixtures live at the FAT root (SEDT.*), and every case re-creates its
 * inputs before running, so leftover state from earlier boots or cases
 * cannot leak in.  Spawn failures under process-table pressure are retried
 * like WCTEST does; a non-empty expected stdout that comes back empty is
 * retried as well, since that is the one scheduler-pressure flake profile
 * the suite has seen.  Empty-stdout cases (q, -i, w-only, errors) are never
 * retried on emptiness.
 *
 * All status output goes to the console (print_console), matching the rest
 * of the test programs — stdout is a pipe owned by this harness.
 */
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/wait.h>
#include <unistd.h>
#include "libc.h" /* pipe(), spawn2(), print_console() */
#include "sed_test_cases.h"

static int failures = 0;

/* tiny signed-int console printer (no libc/sysroot dependency) */
static void con_int(int v) {
  char b[16];
  int i = 15, neg = 0;
  if (v < 0) {
    neg = 1;
    v = (v == -2147483648) ? 2147483647 : -v;
  }
  b[i--] = 0;
  if (v == 0) b[i--] = '0';
  while (v > 0) {
    b[i--] = (char)('0' + v % 10);
    v /= 10;
  }
  if (neg) b[i--] = '-';
  print_console(&b[i + 1]);
}

/* Print up to 48 bytes of s with visible escapes (debug previews). */
static void print_preview(const char *s, size_t n) {
  char b[8];
  size_t i;
  for (i = 0; i < n && i < 48; i++) {
    unsigned char c = (unsigned char)s[i];
    if (c == '\n') {
      print_console("\\n");
    } else if (c == '\t') {
      print_console("\\t");
    } else if (c == '\r') {
      print_console("\\r");
    } else if (c >= 0x20 && c < 0x7f) {
      b[0] = (char)c;
      b[1] = 0;
      print_console(b);
    } else {
      static const char hex[] = "0123456789abcdef";
      b[0] = '\\';
      b[1] = 'x';
      b[2] = hex[(c >> 4) & 0xf];
      b[3] = hex[c & 0xf];
      b[4] = 0;
      print_console(b);
    }
  }
  if (n > 48) print_console("...");
}

/* Next element of a NUL-separated pair list, or NULL when exhausted. */
static const char *pair_iter(const char *pos, const char **data) {
  if (pos == NULL) return NULL;
  if (*pos == '\0') return NULL;
  *data = pos + strlen(pos) + 1;
  return pos;
}

static int write_file(const char *path, const char *data) {
  int fd = open(path, O_WRONLY | O_CREAT | O_TRUNC);
  size_t len = strlen(data), off = 0;
  if (fd < 0) return -1;
  while (off < len) {
    ssize_t w = write(fd, data + off, len - off);
    if (w <= 0) {
      close(fd);
      return -1;
    }
    off += (size_t)w;
  }
  close(fd);
  return 0;
}

/* Read a whole file into buf (NUL-terminated); -1 when it cannot be read. */
static ssize_t read_file(const char *path, char *buf, size_t cap) {
  int fd = open(path, O_RDONLY);
  size_t n = 0;
  if (fd < 0) return -1;
  while (n + 1 < cap) {
    int r = read(fd, buf + n, cap - n - 1);
    if (r <= 0) break;
    n += (size_t)r;
  }
  close(fd);
  buf[n] = '\0';
  return (ssize_t)n;
}

/* Run SED.BIN once with the case args; capture stdout + exit status.
   Returns 0 on a completed run, -1 when the spawn never succeeded. */
static int run_attempt(const char *args, const char *stdin_data, char *out,
                       size_t outsize, size_t *outlen, int *status) {
  int in_p[2], out_p[2];
  int pid;
  size_t n = 0;

  if (pipe(in_p) != 0 || pipe(out_p) != 0) return -1;
  pid = spawn2("SED.BIN", in_p[0], out_p[1], -1, args);
  if (pid <= 0) {
    /* The boot test suite oversubscribes the kernel's 32-block physical
       pool, so SED.BIN spawns can fail (-1) until other programs exit and
       free their blocks; wait for capacity (up to ~2.5 s) before giving
       up on this attempt. */
    int tries = 0;
    while (pid <= 0 && tries < 100) {
      usleep(25000); /* 25 ms */
      pid = spawn2("SED.BIN", in_p[0], out_p[1], -1, args);
      tries++;
    }
  }
  if (pid <= 0) {
    close(in_p[0]);
    close(in_p[1]);
    close(out_p[0]);
    close(out_p[1]);
    return -1;
  }
  close(in_p[0]);
  {
    size_t off = 0, len = strlen(stdin_data);
    int tries = 0;
    while (off < len && tries < 50) {
      ssize_t w = write(in_p[1], stdin_data + off, len - off);
      if (w > 0) {
        off += (size_t)w;
        tries = 0;
        continue;
      }
      if (w == 0) break;
      usleep(2000); /* 2 ms; wait for the reader to attach */
      tries++;
    }
  }
  close(in_p[1]);

  close(out_p[1]);
  while (n + 1 < outsize) {
    int r = read(out_p[0], out + n, outsize - n - 1);
    if (r <= 0) break; /* EOF once the child exits and its pipe fd closes */
    n += (size_t)r;
  }
  close(out_p[0]);
  out[n] = '\0';
  *outlen = n;
  *status = 0;
  {
    int ws = 0;
    waitpid(pid, &ws, 0);
    *status = ws;
  }
  return 0;
}

static void check_fail(const char *name) {
  print_console("[SEDTEST] FAIL ");
  print_console(name);
}

static void run_case(const sed_case_t *tc) {
  char out[4096];
  size_t outlen = 0;
  int status = 0;
  int ok = 1, attempt;
  const char *pos, *data, *entry;
  static const char *const extra_clean[] = {"SEDT.OUT", "SEDT.NOPE"};

  /* fresh fixture state: drop everything this case writes or checks, plus
     outputs from other cases that must be created anew here */
  for (entry = pair_iter(tc->files, &data); entry;
       pos = data + strlen(data) + 1,
           entry = pair_iter(pos, &data)) {
    unlink(entry);
  }
  for (entry = pair_iter(tc->checks, &data); entry;
       pos = data + strlen(data) + 1,
           entry = pair_iter(pos, &data)) {
    unlink(entry);
  }
  for (size_t i = 0; i < sizeof extra_clean / sizeof extra_clean[0]; i++) {
    unlink(extra_clean[i]);
  }
  for (entry = pair_iter(tc->files, &data); entry;
       pos = data + strlen(data) + 1,
           entry = pair_iter(pos, &data)) {
    if (write_file(entry, data) != 0) {
      check_fail(tc->name);
      print_console(" (cannot write ");
      print_console(entry);
      print_console(")\n");
      failures++;
      return;
    }
  }

  /* run; retry both the "spawn starved" and "expected output, got none"
     scheduler flakes */
  for (attempt = 0; attempt < 3; attempt++) {
    if (run_attempt(tc->args, tc->stdin_data, out, sizeof out, &outlen,
                    &status) != 0) {
      if (attempt + 1 < 3) {
        usleep(200000); /* 200 ms; let other programs exit and free blocks */
        continue;
      }
      check_fail(tc->name);
      print_console(" (spawn SED.BIN failed)\n");
      failures++;
      return;
    }
    if (outlen != 0 || tc->want_stdout[0] == '\0') break;
    usleep(30000); /* 30 ms */
  }

  /* stdout bytes */
  if (outlen != strlen(tc->want_stdout) ||
      memcmp(out, tc->want_stdout, outlen) != 0) {
    ok = 0;
    print_console("[SEDTEST] FAIL ");
    print_console(tc->name);
    print_console(" (stdout)\n  got:  \"");
    print_preview(out, outlen);
    print_console("\"\n  want: \"");
    print_preview(tc->want_stdout, strlen(tc->want_stdout));
    print_console("\"\n");
  }

  /* exit status */
  if (!WIFEXITED(status) || WEXITSTATUS(status) != tc->want_status) {
    ok = 0;
    print_console("[SEDTEST] FAIL ");
    print_console(tc->name);
    print_console(" (status) got ");
    con_int(WIFEXITED(status) ? WEXITSTATUS(status) : -1);
    print_console(", want ");
    con_int(tc->want_status);
    print_console("\n");
  }

  /* post-run file expectations */
  for (entry = pair_iter(tc->checks, &data); entry;
       pos = data + strlen(data) + 1,
           entry = pair_iter(pos, &data)) {
    char buf[512];
    ssize_t n = read_file(entry, buf, sizeof buf);
    if (n < 0 || (size_t)n != strlen(data) ||
        memcmp(buf, data, (size_t)n) != 0) {
      ok = 0;
      print_console("[SEDTEST] FAIL ");
      print_console(tc->name);
      print_console(" (file ");
      print_console(entry);
      if (n < 0) {
        print_console(") missing\n");
      } else {
        print_console(")\n  got:  \"");
        print_preview(buf, (size_t)n);
        print_console("\"\n  want: \"");
        print_preview(data, strlen(data));
        print_console("\"\n");
      }
    }
  }

  if (ok) {
    print_console("[SEDTEST] PASS ");
    print_console(tc->name);
    print_console("\n");
  } else {
    failures++;
  }
}

int main(void) {
  unsigned i, total = SED_CASE_COUNT;

  print_console("[SEDTEST] starting: ");
  con_int((int)total);
  print_console(" golden cases from GNU sed 4.8\n");

  for (i = 0; i < total; i++) {
    run_case(&sed_cases[i]);
  }

  if (failures == 0) {
    print_console("[SEDTEST] ALL PASSED (");
    con_int((int)total);
    print_console(" checks)\n");
    exit(0);
  }
  print_console("[SEDTEST] FAILURES: ");
  con_int(failures);
  print_console("\n");
  exit(1);
}
